# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resourses/hmi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 265)
        MainWindow.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 302, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.verticalLayoutWidget_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.movimiento = QtWidgets.QPushButton(self.frame_4)
        self.movimiento.setGeometry(QtCore.QRect(100, 150, 100, 23))
        self.movimiento.setMaximumSize(QtCore.QSize(100, 25))
        self.movimiento.setStyleSheet("background-color: rgb(173, 170, 255);")
        self.movimiento.setObjectName("movimiento")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 281, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setStyleSheet("background-color: rgb(211, 215, 207);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 258, 104))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_25.setMinimumSize(QtCore.QSize(80, 20))
        self.label_25.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_3.addWidget(self.label_25)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_19.setMinimumSize(QtCore.QSize(40, 20))
        self.label_19.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_20.setMinimumSize(QtCore.QSize(40, 20))
        self.label_20.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.q3_lb = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.q3_lb.setEnabled(False)
        self.q3_lb.setMinimumSize(QtCore.QSize(40, 20))
        self.q3_lb.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.q3_lb.setFont(font)
        self.q3_lb.setObjectName("q3_lb")
        self.gridLayout.addWidget(self.q3_lb, 2, 0, 1, 1)
        self.q3 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.q3.setEnabled(False)
        self.q3.setMinimumSize(QtCore.QSize(50, 20))
        self.q3.setMaximumSize(QtCore.QSize(50, 20))
        self.q3.setMinimum(0)
        self.q3.setMaximum(27)
        self.q3.setObjectName("q3")
        self.gridLayout.addWidget(self.q3, 2, 1, 1, 1)
        self.q2 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.q2.setMinimumSize(QtCore.QSize(50, 20))
        self.q2.setMaximumSize(QtCore.QSize(50, 20))
        self.q2.setMinimum(0)
        self.q2.setMaximum(180)
        self.q2.setObjectName("q2")
        self.gridLayout.addWidget(self.q2, 1, 1, 1, 1)
        self.q1 = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.q1.setMinimumSize(QtCore.QSize(50, 20))
        self.q1.setMaximumSize(QtCore.QSize(50, 20))
        self.q1.setMinimum(0)
        self.q1.setMaximum(180)
        self.q1.setObjectName("q1")
        self.gridLayout.addWidget(self.q1, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_17.setMinimumSize(QtCore.QSize(40, 20))
        self.label_17.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(40, 20))
        self.label_13.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(40, 20))
        self.label_8.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.coordX_l = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.coordX_l.setMinimumSize(QtCore.QSize(50, 20))
        self.coordX_l.setMaximumSize(QtCore.QSize(50, 24))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.coordX_l.setFont(font)
        self.coordX_l.setText("")
        self.coordX_l.setObjectName("coordX_l")
        self.gridLayout_4.addWidget(self.coordX_l, 0, 1, 1, 1)
        self.coordY_l = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.coordY_l.setMinimumSize(QtCore.QSize(50, 20))
        self.coordY_l.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.coordY_l.setFont(font)
        self.coordY_l.setText("")
        self.coordY_l.setObjectName("coordY_l")
        self.gridLayout_4.addWidget(self.coordY_l, 1, 1, 1, 1)
        self.coordZ_l = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.coordZ_l.setMinimumSize(QtCore.QSize(50, 20))
        self.coordZ_l.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.coordZ_l.setFont(font)
        self.coordZ_l.setText("")
        self.coordZ_l.setObjectName("coordZ_l")
        self.gridLayout_4.addWidget(self.coordZ_l, 2, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addWidget(self.frame)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 261, 17))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robot Scara"))
        self.movimiento.setText(_translate("MainWindow", "MOVER"))
        self.label_25.setText(_translate("MainWindow", "Angulos (°):"))
        self.label_19.setText(_translate("MainWindow", "q1:"))
        self.label_20.setText(_translate("MainWindow", "q2:"))
        self.q3_lb.setText(_translate("MainWindow", "q3-mm:"))
        self.label_7.setText(_translate("MainWindow", "PTO DE HERRAMIENTA:"))
        self.label_17.setText(_translate("MainWindow", "z:"))
        self.label_13.setText(_translate("MainWindow", "y:"))
        self.label_8.setText(_translate("MainWindow", "x:"))
        self.label.setText(_translate("MainWindow", "ROBOT SCARA - CINEMATICA DIECTA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
